var allFonts = [{
    "published": true,
    "name": "Shahab",
    "title": "شهاب",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "0.0.2",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "ShahabFont",
    "CDNfileName": "shahab.css",
    "donationID": "iEAI"
}, {
    "published": true,
    "name": "Behdad",
    "title": "بهداد",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v1.0.0",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "BehdadFont",
    "CDNfileName": "behdad.css",
    "donationID": "TGCz"
}, {
    "published": true,
    "name": "Nika",
    "title": "نیکا",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v1.5.8",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "NikaFont",
    "CDNfileName": "nika.css",
    "donationID": "3nfs"
}, {
    "published": true,
    "name": "Farbod",
    "title": "فربد",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v3.2.1",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "FarbodFont",
    "CDNfileName": "farbod.css",
    "donationID": "0dqW"
}, {
    "published": true,
    "name": "Noon",
    "title": "نون",
    "note": "فونت مخصوص طبع و نشر قرآن به همراه پشتیبانی از فارسی",
    "about": "",
    "version": "v0.9.2",
    "used": ["Web", "Mobile", "Print"],
    "weights": ["Regular"],
    "repo": "NoonFont",
    "CDNfileName": "noon.css",
    "donationID": "dGT7"
}, {
    "published": true,
    "name": "Ganjnameh",
    "title": "گنجنامه",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v0.0.4",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "GanjnamehFont",
    "CDNfileName": "ganjnameh.css",
    "donationID": "pylv"
}, {
    "published": true,
    "name": "Yekan",
    "title": "یکان",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
        "version":"از سری اولین نسخه‌های اصلاح شده برای وب می‌باشد(به دلیل درخواست فراوان به مجموعه اضافه گردیده است و جز زیر‌مجموعه‌ اصلی خانه فونت محسوب نمی‌شوند)",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular", "Bold"],
    "repo": "YekanFont",
    "CDNfileName": "yekan.css",
    "donationID": ""
}, {
    "published": true,
    "name": "Nazanin",
    "title": "نازنین",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version":"از سری اولین نسخه‌های اصلاح شده برای وب می‌باشد(به دلیل درخواست فراوان به مجموعه اضافه گردیده است و جز زیر‌مجموعه‌ اصلی خانه فونت محسوب نمی‌شوند)",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular", "Bold"],
    "repo": "Nazanin",
    "CDNfileName": "nazanin.css",
    "donationID": ""
}]