var allFonts = [{
    "published": true,
    "name": "Shahab",
    "title": "شهاب",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "0.0.2",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "ShahabFont",
    "CDNfileName": "shahab.css",
    "donationID": "uDag"
}, {
    "published": true,
    "name": "Behdad",
    "title": "بهداد",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v1.0.0",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "BehdadFont",
    "CDNfileName": "behdad.css",
    "donationID": "t95R"
}, {
    "published": true,
    "name": "Nika",
    "title": "نیکا",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v1.5.8",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "NikaFont",
    "CDNfileName": "nika.css",
    "donationID": "VWZB"
}, {
    "published": true,
    "name": "Farbod",
    "title": "فربد",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v3.2.1",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "FarbodFont",
    "CDNfileName": "farbod.css",
    "donationID": "O3ub"
}, {
    "published": true,
    "name": "Noon",
    "title": "نون",
    "note": "فونت مخصوص طبع و نشر قرآن به همراه پشتیبانی از فارسی",
    "about": "",
    "version": "v0.9.2",
    "used": ["Web", "Mobile", "Print"],
    "weights": ["Regular"],
    "repo": "NoonFont",
    "CDNfileName": "noon.css",
    "donationID": "fcWa"
}, {
    "published": true,
    "name": "Ganjnameh",
    "title": "گنجنامه",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "v0.0.4",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular"],
    "repo": "GanjnamehFont",
    "CDNfileName": "ganjnameh.css",
    "donationID": "a5ou"
}, {
    "published": true,
    "name": "Yekan",
    "title": "یکان",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
        "version": "اولین نسخه اصلاح شده برای وب است(به دلیل درخواست فراوان این فونت به مجموعه اضافه شده ات. و جز فونت‌های خانه فونت نیستند)",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular", "Bold"],
    "repo": "YekanFont",
    "CDNfileName": "yekan.css",
    "donationID": ""
}, {
    "published": true,
    "name": "Nazanin",
    "title": "نازنین",
    "note": "فونتی برای تمام مصارف و کاربردها",
    "about": "",
    "version": "اولین نسخه اصلاح شده برای وب است(به دلیل درخواست فراوان این فونت به مجموعه اضافه شده ات. و جز فونت‌های خانه فونت نیستند)",
    "used": ["Web", "Mobile", "Print", "User InterFace"],
    "weights": ["Regular", "Bold"],
    "repo": "Nazanin",
    "CDNfileName": "nazanin.css",
    "donationID": ""
}]